//push
let fruits = ["apple", "banana", "mango"];
fruits.push("orange");
console.log(fruits);
let nums = [1, 2, 3];
nums.push(20);
console.log(nums);
let numbers = [200, 400, 500, 600];
numbers.push(700);
console.log(numbers);
let colors = ["red", "yellow", "green"];
colors.push("black");
console.log(colors);
let devices = ["transistor", "resistor", "capacitor"];
devices.push("diode");
console.log(devices);
let appliances = ["light", "fan", "cooler"];
appliances.push("fridge");
console.log(appliances);
let mobiles = ["redmi", "motorola", "nokia"];
mobiles.push("iphone");
console.log(mobiles);
let topics = ["strings", "arrays", "functions"];
topics.push("recurssion");
console.log(topics);
let laptops = ["lenova", "victus", "pavillion"];
laptops.push("asus");
console.log(laptops);
let signals = ["unitstep", "unitramp", "sinusoidal"];
signals.push("exponential");
console.log(signals);
//pop
let numberss = [1, 4, 6, 7];
numberss.pop();
console.log(numberss);
let users = ["ram", "sam", "tom"];
users.pop();
console.log(users);
let identity = ["guards", "security", "bouncer"];
identity.pop();
console.log(identity);
let subjects = ["ss", "dsp", "awp"];
subjects.pop();
console.log(subjects);
let keys = ["f3", "f4", "f5"];
keys.pop();
console.log(keys);
let chars = ["sui", "riv", "div"];
chars.pop();
console.log(chars);
let lengths = ["4m", "5m", "6m"];
lengths.pop();
console.log(lengths);
let graphs = ["polar", "semi", "normal"];
graphs.pop();
console.log(graphs);
let companys = ["sky", "safari", "priority"];
companys.pop();
console.log(companys);
let phones = ["ram", "rom", "data"];
phones.pop();
console.log(phones);
//shift
let datas = ["ram", "rom", "sram"];
datas.shift();
console.log(datas);
let keyss = ["f4", "f5"];
keyss.shift();
console.log(keyss);
let subjectss = ["awp", "ec", "bee"];
subjectss.shift();
console.log(subjectss);
let companies = ["digit", "tcs", "microsoft"];
companies.shift();
console.log(companies);
let numss = [2, 4, 5, 6];
numss.shift();
console.log(nums);
let script = ["html", "css", "java"];
script.shift();
console.log(script);
let language = ["telugu", "hindi", "english"];
language.shift();
console.log(language);
let languages = ["kannada", "tamil", "malayalam"];
languages.shift();
console.log(languages);
let nume = [2, 6, 8, 9];
nume.shift();
console.log(nume);
let numes = [33, 55, 77, 88];
numes.shift();
console.log(numes);
//unshift

let letters = ["c", "d"];
letters.unshift("a", "b");
console.log(letters);
let days = ["Tue", "Wed"];
days.unshift("Mon");
console.log(days);
let mix = [2, 3];
mix.unshift("start");
console.log(mix);
let colorss = ["blue", "green"];
colorss.unshift("red");
console.log(colorss);
let values = [true, false];
values.unshift("false");
console.log(values);
let names = ["John", "Lee"];
names.unshift("Adharsh");
console.log(names);
let value = [2, 3, 4];
value.unshift(9);
console.log(value);
let letter = ["a", "b", "c"];
letter.unshift("h");
console.log(letter);
let char = [1, 2, 4, 5];
char.unshift(4);
console.log(char);
let team = [1, 9, 0];
team.unshift(8);
console.log(team);
//length

let letts = ["c", "d"];
console.log(letts.length);
let dayss = ["Tue", "Wed"];
console.log(dayss.length);
let mixs = [2, 3];
console.log(mixs.length);
let colorsss = ["blue", "green"];
console.log(colorsss.length);
let valuess = [true, false];
console.log(valuess.length);
let namu = ["John", "Lee"];
console.log(namu.length);
let valu = [2, 3, 4];
console.log(valu.length);
let lett = ["a", "b", "c"];
console.log(lett.length);
let charss = [1, 2, 4, 5];
console.log(charss.length);
let light = [10, 40, 29, 87];
console.log(light.length);
//includs()
let weight = [45, 66, 88, 99, 10];
console.log(weight.includes(45));
let event = ["heads", "tails"];
console.log(event.includes("heads"));
let dates = [1, 2, 7, 8, 28, 30];
console.log(dates.includes(10));
let mass = ["23kg", "24kg", "67"];
console.log(mass.includes("80"));
let character = ["A", "G", "H", "U", "Y"];
console.log(character.includes("A"));
let bodmas = ["add", "sub", "mul", "div"];
console.log(bodmas.includes("bracket"));
let loops = ["for", "while", "dowhile"];
console.log(loops.includes("for"));
let condition = ["if", "ifelse", "elseif"];
console.log(condition.includes("elseif"));
let method = ["pop", "push", "slice"];
console.log(method.includes("shift"));
let methods = ["indexof", "includes", "splice"];
console.log(methods.includes("forEach"));
//indexof()
let things = ["book", "pen", "pencil"];
console.log(things.indexOf("pencil"));
let cars = ["verna", "skoda", "mercedes", "bmw", "maruti"];
console.log(cars.indexOf("bmw"));
let user = ["adarsh", "dileep", "nithin", "baggav", "uday"];
console.log(user.indexOf("uday"));
let username = ["avinash", "charan", "akhil", "rahul", "ajay"];
console.log(username.indexOf("akhil"));
let file = ["html", "css", "javascript", "python"];
console.log(file.indexOf("python"));
let folder = ["loginfolder", "htmlfolder", "jsfolder"];
console.log(folder.indexOf("jsfolder"));
let assign = ["assign1", "assign2", "assign3", "assign4"];
console.log(assign.indexOf("assign4"));
let frequecy = ["2hz", "5hz", "6hz", "67hz"];
console.log(frequecy.indexOf("6hz"));
let primenumber = [1, 3, 5, 7, 11, 13];
console.log(primenumber.indexOf(11));
let naturalnum = [1, 2, 3, 4, 5, 6];
console.log(naturalnum.indexOf(5));
//slice
let serialnum = [1, 2, 3, 4, 5, 6, 7];
let result = serialnum.slice(2, 5);
console.log(result);
let colour = ["red", "green", "white", "yellow"];
let word = colour.slice(-2);
console.log(word);
let words = ["sainath", "venu", "bala"];
let results = words.slice(0, 4);
console.log(words);
let text = ["javascript"];
let neword = text.slice(0, 4);
console.log(text);
let texts = ["toggle", "theme", "methods"];
let newtext = texts.slice(0, 1);
console.log(texts);
let arr = [1, 3, 4, 5, 7];
let res = arr.slice();
console.log(res);
let tax = [23, 34, 27, 30];
let finaltax = tax.slice(1, 2);
console.log(finaltax);
let group = ["a", "b", "c", "m", "n", "Y"];
let finalgroup = group.slice(2, 5);
console.log(finalgroup);
let allfruits = [
  "grapes",
  "watermelon",
  "apple",
  "pomegranate",
  "banana",
  "starberry",
];
let selectedfruits = allfruits.slice(1, 4);
console.log(selectedfruits);
let certificates = ["memo", "resume", "cv", "incertificate", "residence"];
let finalcertificates = certificates.slice(2, 3);
console.log(finalcertificates);
//splice
let numericals = [3, 4, 5, 6, 7, 8, 9];
numericals.splice(1, 3);
console.log(numericals);
let animals = ["dog", "cat", "cow", "camel", "lion"];
animals.splice(1, 3);
console.log(animals);
let positivenum = [1, 3, 4, 5, 6, 7, 9];
positivenum.splice(-1, 1);
console.log(positivenum);
let waveproperties = ["amplitude", "frequency", "mangnitude"];
waveproperties.splice(1, 2);
console.log(waveproperties);
let salad = ["apple", "grapes", "banana"];
salad.splice(1, 0, "orange");
console.log(salad);
let parts = ["clutch", "accelerator", "break", "engine"];
parts.splice(3, 2, "lights");
console.log(parts);
let fuels = ["petrol", "kerosene", "diesel"];
fuels.splice(1, 1);
console.log(fuels);
let terminal = ["run", "go", "view", "selection"];
terminal.splice(3, 3, "toggle");
console.log(terminal);
let colours = ["yellow", "green", "blue", "black"];
colours.splice(3, 3);
console.log(colours);
let a = ["suri", "sunil", "sudheer", "sudheep"];
a.splice(2, 2, "levin");
console.log(a);
//forEach
let num2 = [1, 4, 5, 6, 8, 9];
num2.forEach(function (n) {
  console.log(n);
});

let num3 = [2, 4, 5, 6, 7];
num3.forEach(function (n) {
  console.log(n);
});
